from sulley import *

s_initialize("INVITE")
s_static("INVITE")
s_delim(" ",fuzzable=False)
s_static("sip")
s_delim(":",fuzzable=False)
s_string("800080")
s_delim("@",fuzzable=False)
s_string("hw.com")
s_delim(" ",fuzzable=False)
s_static("SIP/2.0")
s_static("\r\n")

s_static("Via:SIP/2.0/UDP")
s_delim(" ",fuzzable=False)
s_string("hw.com")
s_delim(";",fuzzable=False)
s_static("branch=")
s_string("z9hG4bK776asdhds\r\n")
s_static("Max-Forwards: ")
s_integer("70")
s_static("\r\n")

s_static("To: ")
s_string("Bob")
s_delim(" ",fuzzable=False)
s_static("<sip:")
s_string("bob")
s_delim("@",fuzzable=False)
s_string("hw.com")
s_static(">")
s_delim(";",fuzzable=False)
s_static("tag")
s_delim("=",fuzzable=False)
s_static("\r\n")

s_static("From: ")
s_string("Alice")
s_delim(" ",fuzzable=False)
s_static("<sip:")
s_string("alice")
s_delim("@",fuzzable=False)
s_string("hw.com")
s_static(">")
s_static(";")
s_static("tag")
s_delim("=",fuzzable=False)
s_integer("192834100")
s_static("\r\n")

s_static("Call-ID: ")
s_string("a84b4c76e66710")
s_static("@")
s_string("hw.com")
s_static("\r\n")

s_static("CSeq: ")
s_integer("21345")
s_delim(" ",fuzzable=False)
s_static("INVITE")
s_static("\r\n")

s_static("Contact: ")
s_static("<sip:")
s_string("alice")
s_delim("@",fuzzable=False)
s_string("hw.com")
s_static(">")
s_static("\r\n")

s_static("Content-Type: ")
s_static("application/sdp")
s_static("\r\n")
s_static("Content-Length: ")
s_integer("142")
s_static("\r\n")