# import all of Sulley's functionality
from sulley import *

#Authentication 
########################################################
s_initialize("SMTP_Auth")
s_string("HELO localhost\r\n")
s_string("AUTH")
s_delim(" ")
s_string("LOGIN")
s_static("\r\n")
s_string("AUTH")
s_delim(" ")
s_string("YOYO")
s_static("\r\n")
s_string("AUTH")
s_delim(" ")
s_string("YAYA")
s_static("\r\n")
s_static("QUIT\r\n\r\n\r\n")

#########################################################
# RCTP TO:
s_initialize("SMTP_1")
s_static("HELO");
s_delim(" ")
s_string("localhost")
s_static("\r\n")
s_static("MAIL FROM")
s_delim(":")
s_delim("<")
s_static("bob")
s_delim("@")
s_static("bob")
s_delim(".")
s_static("com")
s_delim(">")
s_static("\r\n")
s_static("RCPT TO:")
s_delim(" ")
s_string("postmaster")
s_delim("@")
s_string("company")
s_delim(".")
s_string("mail")
s_static("\r\n")
s_static("DATA")
s_static("\r\n")
s_string("Message-ID")
s_delim(":")
s_string("123")
s_static("\r\n")
s_string("AAAA")
s_static("\r\n")
s_static(".\r\n")
s_static("QUIT\r\n")

##########################################################3
# MAIL FROM:
s_initialize("SMTP_2")
s_static("HELO");
s_delim(" ")
s_string("localhost")
s_static("\r\n")
s_string("MAIL FROM")
s_delim(":")
s_delim("<")
s_string("bob")
s_delim("@")
s_string("bob")
s_delim(".")
s_string("com")
s_delim(">")
s_static("\r\n")
s_static("RCPT TO:")
s_delim(" ")
s_static("postmaster")
s_delim("@")
s_static("company")
s_delim(".")
s_static("mail")
s_static("\r\n")
s_static("DATA")
s_static("\r\n")
s_static("Message-ID")
s_delim(":")
s_string("123")
s_static("\r\n")
s_string("AAAA")
s_static("\r\n")
s_static(".\r\n")
s_static("QUIT\r\n")
